# Generated by Django 3.1.4 on 2021-09-30 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('picture', models.FileField(blank=True, default='images/default_image.jpg', null=True, upload_to='images')),
                ('description', models.CharField(max_length=200, null=True)),
                ('Created_date', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Religious', 'religious'), ('Hilly', 'hilly'), ('Mountain', 'mountain'), ('Terai', 'terai'), ('FamousDestination', 'famousdestination'), ('JungleSafari', 'junglesafari')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Galary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('number', models.BigIntegerField(blank=True)),
                ('mesge', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='destinations.destinations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
